"""RL post-training contracts.

The stated plan is: pretrain (or load) a VLA, then post-train it with RL inside
environments generated by the world model. This package holds the algorithm side
of that; `src/bridge/` holds the environment side.

Two contracts:

* `RLAlgorithm` -- consumes rollouts, updates the policy. PPO, GRPO, AWR all fit.
* `Rollout`     -- what an environment produces and an algorithm consumes, so the
  same algorithm runs against a simulator or against the world model without
  knowing which.

**Design constraints that come from the setup, and are worth stating plainly:**

1. *The action head must be stochastic.* A `continuous_mse` head has no density,
   so no policy gradient exists. `stage_rl` checks `head.supports_rl` and refuses
   rather than silently optimising nothing.

2. *KL-to-BC is not optional.* RL against a learned reward inside a learned world
   model has two exploitable models. Without a KL penalty anchoring the policy to
   its BC initialisation, it will find the world model's failure modes -- actions
   that are physically nonsense but that the dynamics model happens to score
   well. Keep `kl_coef > 0` and watch `kl_to_ref`.

3. *On-policy is the safer default.* PPO/GRPO regenerate rollouts each iteration,
   so world-model error does not accumulate in a replay buffer the way it does
   with off-policy methods. Sample efficiency is worse; correctness is better,
   and rollouts inside a world model are cheap compared to a simulator.

See `research/020_rl_in_dream.md`.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import torch
import torch.nn as nn

from common.types import Observation
from vla.core.registry import RL_ALGORITHMS


@dataclass
class Rollout:
    """A batch of trajectories. Time-major: (T, N, ...) with N parallel envs."""

    observations: List[Observation]
    actions: torch.Tensor                        # (T, N, action_dim)
    rewards: torch.Tensor                        # (T, N)
    dones: torch.Tensor                          # (T, N) bool
    logps: Optional[torch.Tensor] = None         # (T, N) behaviour policy
    values: Optional[torch.Tensor] = None        # (T, N)
    info: Dict[str, Any] = field(default_factory=dict)

    @property
    def horizon(self) -> int:
        return self.actions.shape[0]

    @property
    def num_envs(self) -> int:
        return self.actions.shape[1]

    def episode_return(self) -> float:
        return float(self.rewards.sum(0).mean())


class RLAlgorithm(ABC):
    """Updates a `VLAPolicy` from rollouts."""

    #: whether this algorithm needs a value function
    needs_critic: bool = True

    def __init__(
        self,
        policy: nn.Module,
        *,
        reference_policy: Optional[nn.Module] = None,
        kl_coef: float = 0.05,
        gamma: float = 0.99,
        lr: float = 1e-5,
    ) -> None:
        if not getattr(policy.head, "supports_rl", False):
            raise ValueError(
                f"{type(policy.head).__name__} has no action distribution. "
                "RL post-training needs head.name=gaussian or discrete_bins; "
                "re-run BC with one of those before post-training."
            )
        self.policy = policy
        self.reference = reference_policy
        self.kl_coef = kl_coef
        self.gamma = gamma
        self.lr = lr

    @abstractmethod
    def update(self, rollout: Rollout) -> Dict[str, float]:
        """One optimisation pass. Returns metrics including `kl_to_ref`."""

    def kl_penalty(self, obs: Observation, actions: torch.Tensor) -> torch.Tensor:
        """KL(current || BC reference), the anchor against reward hacking.

        Returns zero when no reference policy was supplied -- which is a
        deliberate choice the caller has to make, not a default.
        """
        if self.reference is None:
            return torch.zeros((), device=actions.device)
        with torch.no_grad():
            ref_logp = self.reference.sample(obs)[1]
        cur_logp = self.policy.sample(obs).logp
        return (cur_logp - ref_logp).mean()
